apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-odn7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-odn7
    app.kubernetes.io/part-of: tkrw-pr712-0075-0074-app
  name: devfile-sample-odn7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-odn7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-odn7
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-odn7@sha256:9bdb0484b0a9fc24e0d85ffef892b81de40604dbe84433a6d215505fe50155ce
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
